### PR TITLE
 WanderLustJavaScript.js

### PR DESCRIPTION
**Pull request by asmasulaibeekh**
Changing the color of the elements when you click on them 
update the array

### CODE REVIEW

**Comment by asmasulaibeekh** [comment]
update the array

**Comment by asmasulaibeekh** [comment]
add some new things to the elements

**Review by sarahalhammadi — APPROVED** [review]
Great  changes 
good job asma

**Review by Mouza-Ayman-Alsharhan — APPROVED** [review]
Good, I liked that.
Approved!

**Pull request merged**
