### PR TITLE
 UAE-Places.html

### PR DESCRIPTION
**Pull request by asmasulaibeekh**
Upload places

### CODE REVIEW

**Comment by asmasulaibeekh** [comment]
upload pictures

**Comment by asmasulaibeekh** [comment]
add a short paragraph for each title

**Comment by SabaNadeemUOS** [comment]
good

**Review by sarahalhammadi — APPROVED** [review]

**Comment by asmasulaibeekh** [comment]
Modified imp tags

**Comment by asmasulaibeekh** [comment]
Modified image  tags

**Pull request merged**
