### PR TITLE
adding a javascript for top button to navigate to the beginning of th…

### PR DESCRIPTION
**Pull request by SabaNadeemUOS**

### CODE REVIEW

**Review by SabaNadeemUOS — COMMENTED** [review]
`<button onclick="topFunction()" id="myBtn" title="Go to top">^</button>`
The title is the text of the button that will be seen right?

**Comment by Mouza-Ayman-Alsharhan** [comment]
> 

Saba,
no, what is gonna be displayed is the text "^"
have a look at the attched screenshot


Screenshot 2022-11-20 151801

**Comment by SabaNadeemUOS** [comment]
Oh i see now

**Comment by SabaNadeemUOS** [comment]
Maybe we can add a text on hover that says 'Go to Top'?
or is it alright like this
What do you guys think?

**Comment by Mouza-Ayman-Alsharhan** [comment]
> Oh i see now

here is a video that shows how this button works


Uploading About Us - Google Chrome 2022-11-19 19-54-55.mp4…

**Review by Lamyaalmheiri — APPROVED** [review]

**Pull request merged**
